### PR TITLE
Argument unpacking with splat operator

### PR DESCRIPTION
**Pull request by ayushpandey8439**
Simple example of how the splat operator can be used for in-place unpacking of operators

### CODE REVIEW

**Comment by eldhoittangeorge** [comment]
Can you update the readme file also?

**Comment by ayushpandey8439** [comment]
> Can you update the readme file also?

Definitely. 😁

**Comment by ayushpandey8439** [comment]
All done. This should pose no problems now. Thanks :)

**Comment by eldhoittangeorge** [comment]
@ayushpandey8439  Thanks for contributing. If you like the concept consider giving a star.

**Pull request merged**
