### PR TITLE
Add Python way and normal way of calculating Cartesian product

### PR DESCRIPTION
**Pull request by KulkarniSuraj**
Normal way uses **_nested loops_** to to generate all pairs 
Python way uses _**list comprehension**_ as well as built-in function in _**itertools**_ module
name of the file -  `cartesianProduct.py`

**Example of cartesian product**
A = [1, 2, 3]
B = [4, 5]
Cartesian product of A and B _**A X B**_ is **_[(1, 4), (1, 5), (2, 4), (2, 5), (3, 4), (3, 5)]_**

### Pull Request checklist

- [ ] bug fix

- [ ] feature

- [x] enhancement
> _README.md file also updated_

### CODE REVIEW

**Review by eldhoittangeorge — CHANGES_REQUESTED** [review]
Undo the change done on the Zen of Python. Showing it on a list is better.

**Comment by KulkarniSuraj** [comment]
I guess that occured becuase I used `git pull`

**Comment by eldhoittangeorge** [comment]
Fix that, please.

**Comment by KulkarniSuraj** [comment]
Any idea how can I dot it?

**Comment by eldhoittangeorge** [comment]
Add a - before every line and press 'enter' after every line.

**Comment by KulkarniSuraj** [comment]
I am unable to solve the issue.
I don't know what went wrong?
so I am closing this pull request and creating new one

**Pull request closed without merging**
