### PR TITLE
Fixed typos in arrayIteration.py

### LINKED ISSUE #25: Typo in arrayIteration.py

### PR DESCRIPTION
**Pull request by SudhamJayanthi**
Fixes #25

### CODE REVIEW

**Comment by SudhamJayanthi** [comment]
@eldhoittangeorge Kindly review it & label it “hacktober-accepted” when merging it.

**Comment by SudhamJayanthi** [comment]
Thanks @eldhoittangeorge !

**Comment by eldhoittangeorge** [comment]
If you like the concept can you give us a star?

**Comment by SudhamJayanthi** [comment]
Yeah, love the concept!  **Starred it ⭐️** Also could you _suggest me some files_ that you would like me to contribute for ? Because I just came to know that typos may not count towards hacktoberfest.

**Comment by eldhoittangeorge** [comment]
@SudhamJayanthi  I will create an issue and assign that to you.

**Comment by eldhoittangeorge** [comment]
@SudhamJayanthi I have added a new issue do you want to take that up.

**Pull request merged**
